version: '3.1'

services:
  jellyfin:
     image: jellyfin/jellyfin:latest
     ports:
       - 8096:8096
     volumes:
       - ./config/config:/config 
       - ./config/cache:/cache
       - ./config/media:/media
     networks:
       - net
networks:
  net:
